
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[262] =
    {   0,
        0,    0,   92,   92,  100,   98,   97,   97,   59,   98,
       90,   61,   54,   98,   46,   47,   55,   56,   89,   57,
       50,   60,   40,   40,   75,   76,   64,   78,   65,   74,
       38,   44,   45,   70,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       48,   71,   49,   58,   92,   94,   93,   69,    0,   43,
        0,   81,   72,   86,    0,    0,   79,   52,   82,   53,
       83,   51,    0,   41,   91,   96,   80,   41,    0,    0,
       40,   62,   66,   68,   67,   63,   38,   87,   38,   38,
       38,   38,   38,   38,   38,   38,   38,    8,   38,   38,

       38,   38,   38,   38,   16,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   88,   73,   92,   93,
       93,   95,   42,   77,    0,   96,    0,   41,   84,   85,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   14,   38,   38,   18,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,    0,   41,   38,   38,   38,    1,
       38,    3,    4,   38,   38,   38,   38,   10,   11,   38,
       38,   15,   38,   19,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   32,   38,   38,   35,

       38,   38,    2,    5,   38,   38,   38,   38,   13,   38,
       38,   38,   38,   23,   38,   38,   38,   38,   38,   38,
       30,   38,   38,   34,   38,   38,   38,   38,    9,   12,
       17,   38,   38,   22,   24,   25,   26,   27,   28,   38,
       38,   38,   38,   38,   38,    7,   38,   38,   29,   38,
       38,   36,   38,    6,   20,   21,   31,   33,   38,   37,
        0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   28,   26,   29,   26,
       26,   26,   30,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       31,   32,   33,   34,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   26,   45,   46,   47,   48,
       49,   50,   26,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    1,    1,    1,    4,    4,    1,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        1,    1,    1,    1,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[269] =
    {   0,
        0,    0,   61,   62,  360,  488,  488,  488,  335,   70,
      488,  333,   58,   62,  488,  488,  332,   55,  488,   61,
       53,   65,  108,  112,  488,  488,   67,  330,   68,  488,
        0,  488,  488,  329,   66,  297,  299,   65,   60,   86,
       34,  300,   56,  299,  306,  101,  287,  296,  292,  297,
      488,   79,  488,  488,    0,  488,  121,  488,  153,  204,
      255,  488,  488,  488,  306,  357,  488,  488,  488,  488,
      488,  488,  323,  131,  488,    0,  488,  137,  145,  154,
      163,  315,  488,  488,  488,  314,    0,  488,  287,  286,
      287,  280,  292,  278,  293,  280,  286,  272,  273,  270,

      270,  273,  270,  267,    0,   59,  271,   94,  269,   80,
       84,  273,  266,  107,  124,  270,  488,  488,    0,  163,
      171,  488,  408,  488,  178,    0,  168,  180,  488,  488,
      264,  265,  273,  258,  269,  264,  251,  158,  265,  263,
      259,  251,  257,  259,    0,  245,  249,    0,  248,  245,
      235,  233,  235,  237,  244,  230,  228,  228,  239,  229,
      233,  237,  239,  228,  196,  198,  227,  222,  229,    0,
      225,    0,    0,  216,  224,  213,  220,    0,    0,  214,
      210,    0,  214,    0,  209,  207,  205,  201,  213,  202,
      206,  211,  210,  208,  198,  202,    0,  190,  202,    0,

      193,  194,    0,    0,  189,  190,  195,  186,    0,  193,
      179,  187,  182,    0,  189,  186,  188,  172,  181,  183,
        0,  174,  177,    0,  180,  171,  164,  159,    0,    0,
        0,  167,  167,    0,    0,    0,    0,    0,    0,  161,
      160,  149,  127,  140,  125,    0,  102,   89,    0,   90,
       79,    0,   65,    0,    0,    0,    0,    0,   28,    0,
      488,  463,  467,  471,   66,  475,  479,  483
    } ;

static yyconst flex_int16_t yy_def[269] =
    {   0,
      261,    1,  262,  262,  261,  261,  261,  261,  261,  263,
      261,  261,  261,  264,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      265,  261,  261,  261,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      261,  261,  261,  261,  266,  261,  267,  261,  263,  263,
      263,  261,  261,  261,  264,  264,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  268,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  265,  261,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,

      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  261,  261,  266,  267,
      267,  261,  264,  261,  261,  268,  261,  261,  261,  261,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  261,  261,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,

      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
        0,  261,  261,  261,  261,  261,  261,  261
    } ;

static yyconst flex_uint16_t yy_nxt[552] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   31,   31,   31,   31,
       32,    6,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   31,   43,   31,   44,   31,   31,   31,   31,
       45,   46,   47,   48,   49,   50,   31,   31,   31,   51,
       52,   53,   54,   56,   56,   63,   66,   68,   73,   87,
       74,   74,   57,   57,   60,   70,   75,   69,   61,  102,
       64,   76,  103,   71,   72,  260,   66,   77,   82,   83,
       85,   86,   89,   90,   61,   91,  105,   66,   66,   97,

       94,  117,   66,  106,  147,   61,   61,   95,   98,   66,
       61,  148,   66,   96,   66,  259,   66,   61,  258,  156,
       61,  154,   61,   78,   61,   79,   79,   78,  257,   81,
       81,   99,  121,  100,  157,  150,   80,  122,  155,  118,
       80,  256,  101,  109,  110,  151,  152,   80,   74,   74,
      160,   80,  255,  111,   74,   74,  112,   60,  161,  125,
       78,   61,   79,   79,  254,  125,  127,  162,  127,  163,
      125,  128,  128,   80,  261,  253,  125,   61,   78,  261,
       81,   81,  121,  252,   80,  128,  128,  122,   61,   61,
      165,   80,  165,   61,  251,  166,  166,  128,  128,  250,

       61,  249,   80,   61,  248,   61,  247,   61,   60,  174,
      175,  246,   61,  166,  166,  166,  166,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,   61,  234,
      233,  232,  231,  230,  229,  228,  227,  226,  225,   61,
       61,  224,  223,  222,   61,  221,  220,  219,  218,  217,
      216,   61,  215,  214,   61,  213,   61,  212,   61,   60,
      211,  210,  209,   61,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  197,  196,  195,  194,   61,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
       61,   61,  183,  182,  181,   61,  180,  179,  178,  177,

      176,  173,   61,  172,  171,   61,  170,   61,  169,   61,
       66,  168,  167,  164,  123,  159,  158,  153,  149,  146,
      145,  144,  143,  142,  141,  140,  139,  138,  137,  136,
       66,  135,  134,  133,  132,  131,  130,  129,  124,  116,
      115,   66,   66,  114,  113,  108,   66,  107,  104,   93,
       92,   88,   84,   66,   67,   62,   66,   58,   66,  261,
       66,   66,  261,  261,  261,  123,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,   66,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,   66,   66,  261,  261,  261,   66,  261,  261,

      261,  261,  261,  261,   66,  261,  261,   66,  261,   66,
      261,   66,   66,  261,  261,  261,  123,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,   66,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,   66,   66,  261,  261,  261,   66,  261,
      261,  261,  261,  261,  261,   66,  261,  261,   66,  261,
       66,  261,   66,   55,   55,   55,   55,   59,  261,   59,
       59,   65,  261,   65,   65,  119,  261,  261,  119,  120,
      261,  120,  120,  126,  261,  126,  126,    5,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,

      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261
    } ;

static yyconst flex_int16_t yy_chk[552] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,   13,   14,   18,   21,  265,
       21,   21,    3,    4,   10,   20,   22,   18,   10,   41,
       13,   22,   41,   20,   20,  259,   14,   22,   27,   27,
       29,   29,   35,   35,   10,   35,   43,   14,   14,   39,

       38,   52,   14,   43,  106,   10,   10,   38,   39,   14,
       10,  106,   14,   38,   14,  253,   14,   10,  251,  111,
       10,  110,   10,   23,   10,   23,   23,   24,  250,   24,
       24,   40,   57,   40,  111,  108,   23,   57,  110,   52,
       24,  248,   40,   46,   46,  108,  108,   23,   74,   74,
      114,   24,  247,   46,   78,   78,   46,   59,  114,   74,
       79,   59,   79,   79,  245,   78,   80,  115,   80,  115,
       74,   80,   80,   79,  120,  244,   78,   59,   81,  120,
       81,   81,  121,  243,   79,  127,  127,  121,   59,   59,
      125,   81,  125,   59,  242,  125,  125,  128,  128,  241,

       59,  240,   81,   59,  233,   59,  232,   59,   60,  138,
      138,  228,   60,  165,  165,  166,  166,  227,  226,  225,
      223,  222,  220,  219,  218,  217,  216,  215,   60,  213,
      212,  211,  210,  208,  207,  206,  205,  202,  201,   60,
       60,  199,  198,  196,   60,  195,  194,  193,  192,  191,
      190,   60,  189,  188,   60,  187,   60,  186,   60,   61,
      185,  183,  181,   61,  180,  177,  176,  175,  174,  171,
      169,  168,  167,  164,  163,  162,  161,  160,  159,   61,
      158,  157,  156,  155,  154,  153,  152,  151,  150,  149,
       61,   61,  147,  146,  144,   61,  143,  142,  141,  140,

      139,  137,   61,  136,  135,   61,  134,   61,  133,   61,
       65,  132,  131,  116,   65,  113,  112,  109,  107,  104,
      103,  102,  101,  100,   99,   98,   97,   96,   95,   94,
       65,   93,   92,   91,   90,   89,   86,   82,   73,   50,
       49,   65,   65,   48,   47,   45,   65,   44,   42,   37,
       36,   34,   28,   65,   17,   12,   65,    9,   65,    5,
       65,   66,    0,    0,    0,   66,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   66,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   66,   66,    0,    0,    0,   66,    0,    0,

        0,    0,    0,    0,   66,    0,    0,   66,    0,   66,
        0,   66,  123,    0,    0,    0,  123,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  123,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  123,  123,    0,    0,    0,  123,    0,
        0,    0,    0,    0,    0,  123,    0,    0,  123,    0,
      123,    0,  123,  262,  262,  262,  262,  263,    0,  263,
      263,  264,    0,  264,  264,  266,    0,    0,  266,  267,
        0,  267,  267,  268,    0,  268,  268,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,

      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ass6_14CS10062.l"
/*
Name : Sourav Pal
Roll No.: 14CS10062
Assignment No.: 6
Date : 10/11/2016
*/
#line 8 "ass6_14CS10062.l"
	#include "ass6_14CS10062_translator.h"
        #include "y.tab.h"
        #include <string.h>
        #include <stdlib.h>
        #include <vector>
        using namespace std;

#line 689 "lex.yy.c"

#define INITIAL 0
#define comment 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 64 "ass6_14CS10062.l"



#line 912 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 262 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 488 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 67 "ass6_14CS10062.l"
{return AUTO_KEYWORD;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 68 "ass6_14CS10062.l"
{return BREAK_KEYWORD;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 69 "ass6_14CS10062.l"
{return CASE_KEYWORD;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 70 "ass6_14CS10062.l"
{return CHAR_KEYWORD;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 71 "ass6_14CS10062.l"
{return CONST_KEYWORD;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 72 "ass6_14CS10062.l"
{return CONTINUE_KEYWORD;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 73 "ass6_14CS10062.l"
{return DEFAULT_KEYWORD;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 74 "ass6_14CS10062.l"
{return DO_KEYWORD;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 75 "ass6_14CS10062.l"
{return DOUBLE_KEYWORD;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 76 "ass6_14CS10062.l"
{return ELSE_KEYWORD;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 77 "ass6_14CS10062.l"
{return ENUM_KEYWORD;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 78 "ass6_14CS10062.l"
{return EXTERN_KEYWORD;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 79 "ass6_14CS10062.l"
{return FLOAT_KEYWORD;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 80 "ass6_14CS10062.l"
{return FOR_KEYWORD;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 81 "ass6_14CS10062.l"
{return GOTO_KEYWORD;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 82 "ass6_14CS10062.l"
{return IF_KEYWORD;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 83 "ass6_14CS10062.l"
{return INLINE_KEYWORD;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 84 "ass6_14CS10062.l"
{return INT_KEYWORD;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 85 "ass6_14CS10062.l"
{return LONG_KEYWORD;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 86 "ass6_14CS10062.l"
{return REGISTER_KEYWORD;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 87 "ass6_14CS10062.l"
{return RESTRICT_KEYWORD;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 88 "ass6_14CS10062.l"
{return RETURN_KEYWORD;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 89 "ass6_14CS10062.l"
{return SHORT_KEYWORD;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 90 "ass6_14CS10062.l"
{return SIGNED_KEYWORD;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 91 "ass6_14CS10062.l"
{return SIZEOF_KEYWORD;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 92 "ass6_14CS10062.l"
{return STATIC_KEYWORD;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 93 "ass6_14CS10062.l"
{return STRUCT_KEYWORD;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 94 "ass6_14CS10062.l"
{return SWITCH_KEYWORD;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 95 "ass6_14CS10062.l"
{return TYPEDEF_KEYWORD;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 96 "ass6_14CS10062.l"
{return UNION_KEYWORD;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 97 "ass6_14CS10062.l"
{return UNSIGNED_KEYWORD;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 98 "ass6_14CS10062.l"
{return VOID_KEYWORD;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 99 "ass6_14CS10062.l"
{return VOLATILE_KEYWORD;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 100 "ass6_14CS10062.l"
{return WHILE_KEYWORD;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 101 "ass6_14CS10062.l"
{return _BOOL_KEYWORD;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 102 "ass6_14CS10062.l"
{return _COMPLEX_KEYWORD;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 103 "ass6_14CS10062.l"
{return _IMAGINARY_KEYWORD;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 105 "ass6_14CS10062.l"
{(yylval.atr_val).name = strdup(yytext);return IDENTIFIER;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 106 "ass6_14CS10062.l"
{yylval.enum_val  =  yytext;       return ENUMERATION_CONSTANT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 107 "ass6_14CS10062.l"
{yylval.int_val   =  atoi(yytext); return INTEGER_CONSTANT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 108 "ass6_14CS10062.l"
{yylval.float_val =  atof(yytext); return FLOATING_CONSTANT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 109 "ass6_14CS10062.l"
{yylval.char_val  =  yytext[1];    return CHAR_CONSTANT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 110 "ass6_14CS10062.l"
{yylval.str_val   =  yytext;       return STRING_LITERAL;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 112 "ass6_14CS10062.l"
{return LEFT_SQUARE_BRACE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 113 "ass6_14CS10062.l"
{return RIGHT_SQUARE_BRACE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 114 "ass6_14CS10062.l"
{return LEFT_ROUND_BRACE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 115 "ass6_14CS10062.l"
{return RIGHT_ROUND_BRACE;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 116 "ass6_14CS10062.l"
{return LEFT_CURLY_BRACE;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 117 "ass6_14CS10062.l"
{return RIGHT_CURLY_BRACE;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 118 "ass6_14CS10062.l"
{return PERIOD;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 120 "ass6_14CS10062.l"
{return POINTS_TO;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 121 "ass6_14CS10062.l"
{return PLUS_PLUS;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 122 "ass6_14CS10062.l"
{return MINUS_MINUS;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 123 "ass6_14CS10062.l"
{return AMPERSAND;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 124 "ass6_14CS10062.l"
{return MULTIPLICATION;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 125 "ass6_14CS10062.l"
{return PLUS;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 126 "ass6_14CS10062.l"
{return MINUS;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 127 "ass6_14CS10062.l"
{return TILDE;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 128 "ass6_14CS10062.l"
{return EXCLIMATION;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 129 "ass6_14CS10062.l"
{return FORWARD_SLASH;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 130 "ass6_14CS10062.l"
{return PERCENTAGE;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 132 "ass6_14CS10062.l"
{return LEFT_SHIFT;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 133 "ass6_14CS10062.l"
{return RIGHT_SHIFT;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 134 "ass6_14CS10062.l"
{return LESS_THAN;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 135 "ass6_14CS10062.l"
{return GREATER_THAN;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 136 "ass6_14CS10062.l"
{return LESS_THAN_EQUAL;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 137 "ass6_14CS10062.l"
{return GREATER_THAN_EQUAL;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 138 "ass6_14CS10062.l"
{return EQUAL_EQUAL;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 139 "ass6_14CS10062.l"
{return NOT_EQUAL;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 141 "ass6_14CS10062.l"
{return CARET;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 142 "ass6_14CS10062.l"
{return BITWISE_OR;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 143 "ass6_14CS10062.l"
{return LOGICAL_AND;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 144 "ass6_14CS10062.l"
{return LOGICAL_OR;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 145 "ass6_14CS10062.l"
{return QUESTION_MARK;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 146 "ass6_14CS10062.l"
{return COLON;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 147 "ass6_14CS10062.l"
{return SEMICOLON_TERMINATOR;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 148 "ass6_14CS10062.l"
{return ELIPSES;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 149 "ass6_14CS10062.l"
{return EQUAL;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 151 "ass6_14CS10062.l"
{return MULTIPLICATION_EQUAL;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 152 "ass6_14CS10062.l"
{return SLASH_EQUAL;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 153 "ass6_14CS10062.l"
{return PERCENTAGE_EQUAL;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 154 "ass6_14CS10062.l"
{return PLUS_EQUAL;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 155 "ass6_14CS10062.l"
{return MINUS_EQUAL;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 157 "ass6_14CS10062.l"
{return LEFT_SHIFT_EQUAL;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 158 "ass6_14CS10062.l"
{return RIGHT_SHIFT_EQUAL;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 159 "ass6_14CS10062.l"
{return BITWISE_AND_EQUAL;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 160 "ass6_14CS10062.l"
{return BITWISE_NOT_EQUAL;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 161 "ass6_14CS10062.l"
{return BITWISE_OR_EQUAL;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 162 "ass6_14CS10062.l"
{return COMMA;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 163 "ass6_14CS10062.l"
{return HASH;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 166 "ass6_14CS10062.l"
BEGIN(comment);
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 167 "ass6_14CS10062.l"

	YY_BREAK
case 93:
YY_RULE_SETUP
#line 168 "ass6_14CS10062.l"

	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 169 "ass6_14CS10062.l"

	YY_BREAK
case 95:
YY_RULE_SETUP
#line 170 "ass6_14CS10062.l"
BEGIN(INITIAL);	
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 171 "ass6_14CS10062.l"
{}
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 172 "ass6_14CS10062.l"
{}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 173 "ass6_14CS10062.l"
{}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 175 "ass6_14CS10062.l"
ECHO;
	YY_BREAK
#line 1466 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 262 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 262 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 261);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 175 "ass6_14CS10062.l"





















